CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "connector_type" VARCHAR(255) NOT NULL CHECK ("connector_type" <> '')
);

-- Add a unique constraint if connector_type should be unique
-- ALTER TABLE "Users" ADD CONSTRAINT unique_connector_type UNIQUE ("connector_type");

-- Add an index for better performance on connector_type column if it's frequently queried
CREATE INDEX idx_connector_type ON "Users" ("connector_type");
